### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by SeoNuclear** [younasiqw/IP-traffic-separation#1]
hello
I need to ask you a private question, please can you send me your discord?
The discord contact icon in your profile is wrong.

**Comment by younasiqw** [comment]
Mr.Hokusai#1321
@maurouy

**Comment by SeoNuclear** [comment]
no work Sr. Hokusai#1321

**Comment by younasiqw** [comment]
It is recommended to try again, or u provide ur ID

**Comment by maurouy** [comment]
IAN#1265
